"""The ``?`` key sheet, GENERATED from the live binding table.

A hand-written help screen drifts: the old tree carried a static
HelpScreen plus a hand-fed KeyHelpScreen while its real bindings were
scattered over three layers (some ``show=False``). This overlay is a pure
projection of Textual's ``active_bindings`` — the same chain the key
dispatcher walks (focused widget → screen → app) — so a binding declared
anywhere appears with no edit here, and a removed one disappears. That is
the blueprint's "help generated by the live key table" (§3); the pin that
makes drift impossible is ``tests/test_help_overlay.py`` (M3 acceptance:
the sheet contains every bound key).

Contract notes:

- The shell captures the rows from the screen UNDERNEATH before pushing,
  so the sheet describes that screen's keys, never its own.
- The app-level ``?`` binding is priority (the only way it reaches modal
  screens — Textual cuts the non-priority chain at the last modal), which
  makes the shell action a TOGGLE: ``?`` closes the sheet it opened. A
  focused ``Input`` (regex filter, command bar, palette) still keeps
  ``?`` as text: Textual strips Input-consumed keys from the binding
  chain before any dispatch, priority included.
- Read-only chrome: ``?`` and Esc dismiss; nothing else is bound here.
- Over the ``ConfirmDialog`` the sheet REFUSES (notify): Textual's
  ``Screen.dismiss()`` pops the TOPMOST screen, so a dialog resolving
  under a cover (its fail-closed silence) would pop the wrong screen
  and strand the spent dialog — inert and unclosable. The ONE write
  path keeps its modal surface clean; the refusal is pinned in
  ``tests/test_delete_pilot.py``.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import TYPE_CHECKING, ClassVar, NamedTuple

from rich.table import Table
from rich.text import Text
from textual.binding import Binding
from textual.containers import Container, VerticalScroll
from textual.screen import ModalScreen
from textual.widgets import Footer, Static

from interface.render.tokens import token

if TYPE_CHECKING:  # pragma: no cover - typing only, never imported at runtime
    from textual.screen import ActiveBinding

__all__ = ["HelpOverlay", "KeyRow", "help_rows"]


class KeyRow(NamedTuple):
    """One generated sheet row: the display key, its description, and
    whether the binding's action is currently enabled."""

    key: str
    description: str
    enabled: bool


def help_rows(
    active: Mapping[str, ActiveBinding],
    key_display: Callable[[Binding], str],
) -> tuple[KeyRow, ...]:
    """Pure projection: the live binding table -> deterministic sheet rows.

    ``key_display`` is injectable (the app's ``get_key_display`` in
    production) so the projection is testable without booting an app.
    A binding with no description falls back to its action name — every
    row must say something honest. Rows sort by display key so one
    binding table always yields the same sheet.
    """
    rows = [
        KeyRow(
            key=key_display(entry.binding),
            description=entry.binding.description or entry.binding.action,
            enabled=entry.enabled,
        )
        for entry in active.values()
    ]
    return tuple(sorted(rows, key=lambda row: (row.key.lower(), row.key)))


class HelpOverlay(ModalScreen[None]):
    """The generated key sheet: ``?`` or Esc closes; read-only chrome."""

    BINDINGS: ClassVar[list[Binding]] = [
        Binding("escape", "dismiss", "Close the key sheet"),
        Binding("question_mark", "dismiss", "Close the key sheet"),
    ]
    CSS = """
    #help-modal { align: center middle; }
    #help-body {
        width: auto;
        max-width: 90%;
        max-height: 80%;
        border: round $panel-border;
        border-title-color: $panel-title;
        padding: 0 2;
        background: $surface;
        color: $text-primary;
    }
    """

    def __init__(self, rows: tuple[KeyRow, ...], *, title: str) -> None:
        super().__init__()
        #: Test observability + the sheet's single source: the projection.
        self.rows = rows
        self._title = title

    def compose(self):
        with Container(id="help-modal"), VerticalScroll(id="help-body"):
            yield Static(self._sheet())
        yield Footer()

    def on_mount(self) -> None:
        self.query_one("#help-body", VerticalScroll).border_title = (
            self._title)

    def _sheet(self) -> Table:
        table = Table(box=None, pad_edge=False, show_header=False)
        table.add_column("key", style=f"bold {token('accent')}")
        table.add_column("action", style=token("text.primary"))
        for row in self.rows:
            description = Text(row.description)
            if not row.enabled:
                # A currently-disabled action stays listed (the table is
                # live, not curated) but reads muted.
                description.stylize(token("text.muted"))
            table.add_row(row.key, description)
        return table

    def action_dismiss(self) -> None:
        self.dismiss(None)
